### ISSUE TITLE
timer bell not taking stop input

### ISSUE THREAD

**Issue by austindmello** [Sirimangalo/meditation-plus-angular#200] opened 2016-08-20 17:57 UTC
If one stops a meditation session in between for any reason, the system correctly takes the time meditated and stops the current session , however the timer alarm does not seem to take this input as it goes off  when the original time set in is up. like running a concurrent session that has actually been stopped.

**Comment by binarious** [comment] 2016-08-20 17:59
Duplicate of https://github.com/Sirimangalo/meditation-plus-angular/issues/191.

**Closed by binarious** 2016-08-20 17:59 UTC
Labels: duplicate

**Comment by austindmello** [comment] 2016-08-20 18:01
Ah ,did not see that ... Thanks ..

**Comment by binarious** [comment] 2016-08-20 18:02
No problem. Thanks for informing us! :).
