### ISSUE TITLE
current release very laggy

### ISSUE THREAD

**Issue by ryank85** [Sirimangalo/meditation-plus-angular#188] opened 2016-08-18 01:52 UTC
Running the webapp on my droid maxx phone android OS 4.4.4, the current release is very laggy for me. In particular, if i try to even "click" on the text box within the chat tab to input text, the entire webapp freezes. Tried reproducing in safe mode; entire webapp still very laggy, but not quite so. This leads me to believe that some change with the most recent release has caused this effect.

**Comment by binarious** [comment] 2016-08-18 08:09
Duplicate of https://github.com/Sirimangalo/meditation-plus-angular/issues/185.
Thanks for confirming.

**Closed by binarious** 2016-08-18 08:09 UTC
Labels: duplicate

**Comment by ryank85** [comment] 2016-08-19 16:16
@binarious   was this issue supposed to have been fixed already? Yesterday it was fine for me, but today it's back to being laggy/freezing.

**Comment by binarious** [comment] 2016-08-19 18:56
Fixed but not released. Will do asap.

**Comment by binarious** [comment] 2016-08-19 21:16
It's released now. V1.2.1

ryank85 <notifications@github.com> schrieb am Fr., 19. Aug. 2016 18:16:
