### ISSUE TITLE
The timer is not working correctly I think

### ISSUE THREAD

**Issue by medhinidotnet** [Sirimangalo/meditation-plus-angular#108] opened 2016-08-10 10:54 UTC
This morning I entered a 30 min walk and 30 min sitting meditation. After hitting that button with the clock I get this page with a countdown timer.
In this case it said '60 min left'. So far so good. But after I finished my walking meditation of 30 min it said '54 min left'.

So, I think somewhere in the back it's not working correctly. Or the back/counting is working, but it's not represented correctly on the page (doesn't reload or whatever)?

**Comment by olastor** [comment] 2016-08-10 11:46
Can you provide some information about your system (PC/Smartphone, Operating System, Browser)?

**Comment by medhinidotnet** [comment] 2016-08-10 12:22
system: Mac OS X El Capitan, version 10.11.6, on a MacBook Air
browser: Google Chrome, version 51.0.2704.103 (64-bit)

Just let me know if you need more info. :)

**Comment by binarious** [comment] 2016-08-10 12:55
Did this happen just once? It could have been a connection interruption, because the client does not count for itself. It just requests the server every minute. I'm closing this for now. Feel free to reopen when you can reproduce the issue and you are sure it's not a connectivity problem.

**Comment by medhinidotnet** [comment] 2016-08-11 10:58
No idea how to reopen this thing.

During sitting meditation yesterday evening I watched the clock on the page, the laptop clock and the wifi connection for 5 min.
The connection was on for the entire time, the page did, however, not refresh every minute as I understand it should.

I made 6 screenshot. Hope you can use .png
![01 time 22-21 and time left 56min](https://cloud.githubusercontent.com/assets/20887392/17586631/3684529c-5fc3-11e6-8406-8b3cb424715d.png)
![02 time 22-22 and time left 56min](https://cloud.githubusercontent.com/assets/20887392/17586632/3685e242-5fc3-11e6-9121-25e3fc05db2a.png)
![03 time 22-22 and time left 49 min](https://cloud.githubusercontent.com/assets/20887392/17586634/368a3270-5fc3-11e6-99a5-ff9562479f02.png)
![04 time 22-23 and time left 49min](https://cloud.githubusercontent.com/assets/20887392/17586633/3689aabc-5fc3-11e6-81c3-06ff1664a574.png)
![05 time 22-24 and time left 49min](https://cloud.githubusercontent.com/assets/20887392/17586635/368d1d1e-5fc3-11e6-9ca0-42b6b97f09a0.png)
![06 time 22-25 and time left 49min](https://cloud.githubusercontent.com/assets/20887392/17586636/368d4b2c-5fc3-11e6-9168-3e52cf24c9f6.png)

**Comment by olastor** [comment] 2016-08-12 13:39
I can confirm. I set the timer to 1min but it took 1min 20sec.
![bildschirmfoto von 2016-08-12 15-07-18](https://cloud.githubusercontent.com/assets/7479641/17623924/c984c6aa-60a2-11e6-9c8a-46f10f292c05.png)
@binarious Could this be because of #104 ?

**Comment by binarious** [comment] 2016-08-12 16:24
I think the problematic part is https://github.com/Sirimangalo/meditation-plus-angular/blob/master/src/app/meditation/meditation.component.ts#L160. Will refactor this later today.

**Closed** 2016-08-12 21:34 UTC
Labels: bug
