### ISSUE TITLE
Ability to reset password

### ISSUE THREAD

**Issue by yuttadhammo** [Sirimangalo/meditation-plus-angular#134] opened 2016-08-14 00:48 UTC
Someone mentioned to me that there is no "Forgot your password?" function... is this true?

**Comment by binarious** [comment] 2016-08-14 06:09
Yes, we're waiting for the smtp server. 
Duplicate of https://github.com/Sirimangalo/meditation-plus-angular/issues/27

**Closed by binarious** 2016-08-14 06:09 UTC
Labels: duplicate
