### ISSUE TITLE
Change schedule to stick to Eastern time

### ISSUE THREAD

**Issue by yuttadhammo** [Sirimangalo/meditation-plus-angular#341] opened 2016-11-06 11:20 UTC
Could we possibly adjust the schedule so it adapts to changes in Eastern time? Otherwise, i have to alter my schedule or change each of the dates individually...

**Comment by binarious** [comment] 2016-11-06 15:09
Duplicate of #153. Will look into it asap.

**Closed by binarious** 2016-11-06 15:09 UTC
